config/routes.rb
Rails.application.routes.draw do

  root 'locations#index'

  resources :users, only: [:new, :create]
  resources :locations

  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  post 'login', to: 'sessions#create'

  get 'locations/:id/comment',  to: 'locations#new_comment', as: :new_comment
  post 'locations/:id/comment', to: 'locations#create_comment'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true, length: {minimum: 2}
  belongs_to :user
  belongs_to :location
end

app/models/location.rb
class Location < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5, maximum: 256}
  validates :address, presence: true, length: { minimum: 10, maximum: 256}
  validates :category, presence: true, length: { minimum: 5, maximum: 256}
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness:true, length: { minimum: 4, maximum: 25}
  validates :password, presence: true, length: { minimum: 8, maximum: 30}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :logged_out?
  helper_method :is_admin?

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_out?
    current_user.nil?
  end

  def is_admin?
    unless logged_out?
      current_user.admin
    end
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @location = Location.all
  end

  def new
  end

  def show
    @location = Location.find(params[:id])
  end

  def create
    @location = Location.new(location_params)
    @location.save
    redirect_to @location
  end

  def edit
    @location = Location.find(params[:id])
  end

  def update
    @location = Location.find(params[:id])
    if(@location.update(location_params))
      redirect_to @location
    else
      render 'edit'
    end
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy
    redirect_to @location
  end

  def new_comment
      @comment = nil
  end

  def create_comment
      @location = Location.find(params[:id])
      @comment = @location.comments.new(comment_params)
      @comment.user = current_user
      @comment.save
      redirect_to @location
  end

  private

  def location_params
    params.require(:location).permit(:title, :address, :category, :description)
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
   @user = User.where({username: params[:user][:username], password: params[:user][:password]}).first
   unless @user.nil?
      session[:user_id] = @user.id
      redirect_to '/'
   else
      redirect_to '/login'
   end
  end

  def destroy
    session.delete(:user_id)
    redirect_to '/'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if(@user.save)
      redirect_to '/'
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :admin)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KhmelGuide</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="site-header sticky-top py-1">
  <div class="container d-flex flex-column flex-md-row justify-content-between">
    <span class="py-2 d-none d-md-inline-block"><strong><%= link_to 'ХмельГайд', root_path %></strong></span>
    <% if logged_out? %>
      <span class="py-2 d-none d-md-inline-block"><%= link_to 'Авторизація', login_path %></span>
      <span class="py-2 d-none d-md-inline-block"><%= link_to 'Реєстрація', new_user_path %></span>
    <% else %>
      <% if is_admin? %>
        <span class="py-2 d-none d-md-inline-block"><%= link_to 'Додати локацію', new_location_path %></span>
      <% end %>
      <span class="py-2 d-none d-md-inline-block"><%= link_to 'Вийти', logout_path %></span>
    <% end %>
  </div>
</nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/locations/edit.html.erb
<h2>Редагувати локацію</h2>
<%= form_for :location, url: location_path(@location), method: :patch do |f| %>
  <p> Назва:<br>
    <%= f.text_field :title, :class => "form-control" %>
  </p>
  <p> Адреса:<br>
    <%= f.text_field :address, :class => "form-control" %>
  </p>
  <p> Категорія:<br>
      <%= f.text_field :category, :class => "form-control" %>
  </p>
  <p> Опис:<br>
    <%= f.text_area :description, :class => "form-control" %>
  </p>
  <p><%= f.submit 'Редагувати локацію', :class => "btn btn-outline-primary" %></p>
<% end %>

app/views/locations/index.html.erb
<% @location.each do |l| %>
<div class="card mb-4">
  <div class="card-header">
  <h5 class="my-0 font-weight-normal"><%= l.title%> <small><mark><%= l.category %></mark></small></h5>
  <small class="text-muted"><%= l.address %></small>
  </div>
  <div class="card-body">
  <p><%= l.description %></p>
  <span class="btn btn-outline-primary">  <%= link_to 'Детальніше >>', location_path(l) %></span>
  </div>
</div>
<% end %>

app/views/locations/new.html.erb
<h2>Створити локацію</h2>
<%= form_for :location, url: locations_path do |f| %>
  <p> Назва:<br>
  <%= f.text_field :title, :class => "form-control" %>
  </p>
  <p> Адреса:<br>
  <%= f.text_field :address, :class => "form-control" %>
  </p>
  <p> Ключове слово:<br>
  <%= f.text_field :category, :class => "form-control" %>
  </p>
  <p> Опис:<br>
  <%= f.text_area :description, :class => "form-control" %>
  </p>
  <p><%= f.submit 'Створити локацію', :class => "btn btn-outline-primary" %></p>
<% end %>

app/views/locations/new_comment.html.erb
<h2>Додати коментар</h2>
<%= form_for :comment do |f| %>
  <%= f.text_area :body, :required => "true", :class => "form-control" %>
  <%= f.submit "Додати коментар", :class => "btn btn-outline-primary" %>
<% end %>

app/views/locations/show.html.erb
<div class="card mb-4">
  <div class="card-header">
  <h5 class="my-0 font-weight-normal"><%= @location.title%> <small><mark><%= @location.category %></mark></small></h5>
  <small class="text-muted"><%= @location.address %></small><br><br>
  <% if is_admin? %>
  <%= link_to "Редагувати", edit_location_path(@location), class: "btn btn-outline-warning btn-sm" %>
  <%= link_to "Видалити", @location, data: { method: :delete }, class: "btn btn-outline-danger btn-sm" %>
  <% end %>
  </div>
  <div class="card-body">
  <p><%= @location.description %></p>
  </div>
</div>
<h5>Коментарі</h5>
<% unless logged_out? %>
  <% @location.comments.each do |c| %>
    <p><strong><%= c.user.username %></strong>: <muted><%= c.body %></muted></p>
  <% end %>
  <%= link_to "Додати коментар", :new_comment, class: "btn btn-outline-primary btn-sm" %>
<% else %>
  <p>Коментарі можуть переглядати лише авторизовані користувачі.</p>
<% end %>

app/views/users/new.html.erb
<h1>Зареєструватись</h1>
<%= form_for @user do |f|%>
  <p> Логін: <br>
  <%= f.text_field :username, :class => "form-control" %>
  </p>
  <p> Пароль: <br>
  <%= f.password_field :password, :class => "form-control" %>
  </p>
  <%= f.hidden_field :admin, :value => false %>
  <%= f.submit 'Зареєструватись', :class => "btn btn-outline-primary" %>
<%end%>